### ISSUE TITLE
Raw output for Find-FIDOKey

### ISSUE THREAD

**Issue by dodexahedron** [DevClate/EntraFIDOFinder#15]
This is a handy module for making the human-unfriendly management of FIDO keys more human-friendly. Thanks!

But the output of Find-FIDOKey being forced to a formatted list or table does make it a lot less convenient for use in a pipeline or script.

Can a switch be added to just output that `$results` hashtable raw or make the default be that unless the `-View` parameter is explicitly specified?

One example use case is if you already have a list of AAUIDs you currently use in your environment and want to filter the output of that function against that list, which was what I was trying to do but had to just drop to loading and filtering from the json file to accomplish.

**Comment by dodexahedron** [comment]
Another thought, to avoid the need for as much work on the output (semi-related):

If the types were formalized and a ps1xml provided, that would make formatting the output formatting be implicit unless overridden by the user, and remove the need for helper methods to build the output.

**Comment by DevClate** [comment]
Definitely! When I first started making the PowerShell module I didn't have all the raw data from the FIDO Alliance, and I was thinking of making it more human friendly as you mentioned, but I like your idea of using a switch for the raw output.

You were reading my mind with the AAGUID, as I just started working on making it so you could enter 1 or many AAGUID and get the results just for those and filter them.

Appreciate the feedback, and looking forward to more and getting this resolved.

**Comment by DevClate** [comment]
> Another thought, to avoid the need for as much work on the output (semi-related):
> 
> If the types were formalized and a ps1xml provided, that would make formatting the output formatting be implicit unless overridden by the user, and remove the need for helper methods to build the output.

And I just uploaded the refactored function on the development branch, you can check here [Development Branch](https://github.com/DevClate/EntraFIDOFinder/blob/development/Functions/Public/Find-FIDOKey.ps1)

If you don't put view, it will give you an object that you can pipe through more easily. Also if you use -AllProperties, it will show you the whole json FIDO Alliance information formatted in Json(working on getting them into a nice pscustomobject or hashtable. Are there any properties you would want to see first? I did add the newest FIDO Version of each key in the "basic" view.

Any feedback is greatly appreciated!

**Comment by DevClate** [comment]
This will be fixed in v0.0.14 :)

**Comment by DevClate** [comment]
Fixed with v0.0.14

**Comment by dodexahedron** [comment]
Sorry for the late reply. Just been too busy to check my github inbox recently. 😅

In any case, I'll check out the latest release shortly, but figured I'd respond to your questions at least:

> Would having ImportExcel as a requirement be an issue?

I'd _personally_, for any ps module I use, prefer a minimum of dependencies if possible, since I'm a fan of being able to use PowerShell on multiple platforms, and my daily driver is booted to Linux like 40% of the time, or I may be writing scripts that need to be able to run on any platform (this one is more niche, but I mean in general anyway).

You might already be fully aware of this, but if not here is a cool thing anyway:\
For excel files, csv, tab-delimited files, SQL databases, NoSQL databases, or anything else that can be accessed via ODBC with anything already installed on the machine, you can actually do it without any other module or nuget dependencies right from .net, by just using an ODBC Connection (and can of course include your default driver dependency, if any, but csv doesn't need one anyway).

When you use an ODBCConnection with flat files, rather than an actual database, it is presented to you as if the names of the files are table names or, in the case of excel files that have multiple worksheets, the worksheets are tables. You can use standard SQL syntax with it - like `SELECT someColumn from someFile.csv WHERE someOtherColumn=@someParameterBecauseNobodyLikesSQLInjection` - which is awesome because it means you can just use one set of queries and it will work on _any_ datastore the client can support, even if you have to change where you get your data from at some point! You can also use EFCore with that, which is a nuget dependency, yes, but is cross-platform and probably already in everyone's nuget cache anyway. 😊

Absent that, as long as you don't list that dependency as a hard dependency via a `#require` or using or anything, it shouldn't be a problem for PowerShell unless someone calls a method that tries to use it, in which case they should get a pretty clear error that the required module is missing.

**Comment by dodexahedron** [comment]
> > Another thought, to avoid the need for as much work on the output (semi-related):
> > If the types were formalized and a ps1xml provided, that would make formatting the output formatting be implicit unless overridden by the user, and remove the need for helper methods to build the output.
> 
> And I just uploaded the refactored function on the development branch, you can check here [Development Branch](https://github.com/DevClate/EntraFIDOFinder/blob/development/Functions/Public/Find-FIDOKey.ps1)
> 
> If you don't put view, it will give you an object that you can pipe through more easily. Also if you use -AllProperties, it will show you the whole json FIDO Alliance information formatted in Json(working on getting them into a nice pscustomobject or hashtable. Are there any properties you would want to see first? I did add the newest FIDO Version of each key in the "basic" view.
> 
> Also now if you use -DetailedProperties all properties are available with select-object and filtering.
> 
> Any feedback is greatly appreciated!

I'll have a look in a bit (assuming I don't forget, since I'm multitasking this with more urgent work at the moment).

Even if not perfect, any additions like that sound like they'll still be quite handy to have available!

**Comment by dodexahedron** [comment]
Oh and again just wanted to say thanks!

Things like this, while maybe not the most advanced CryptoCloudAIBlockChainAndOtherBuzzWords_4.20, are seriously the things that make life better when someone comes along, sucks it up, DOES them, and then SHARES them with the rest of us lazy folks. 😅 

And then responding to feedback? Want a beer? Next one's on me. 😄
