### ISSUE TITLE
Add company URLs

### ISSUE THREAD

**Issue by DevClate** [DevClate/EntraFIDOFinder#2]
Add at least company URLs for each key. Ideally, I'd love to have direct links to each, but maybe way to time consuming. Thoughts?

**Comment by dodexahedron** [comment]
Potentially a lot of effort for something that might not be very durable, as companies make changes to their websites and break existing links. Unless you just mean their home pages. But that wouldn't really be worth the time, I don't think. 🤷‍♂️
