### ISSUE TITLE
Include FIDO version supported (if known)

### ISSUE THREAD

**Issue by matthew-armitage-steeves** [DevClate/EntraFIDOFinder#9]
FIDO 2.1 has some key improvements for users with many stored credentials, including support for removing individual credentials without an entire reset. This info would be great to have as token differentiator.

**Comment by DevClate** [comment]
Thanks Matt! Let me check and see if there is a way to easily check that, it may be a manual process. Do you have a preference if it’s on the web version or PowerShell version first?

**Comment by matthew-armitage-steeves** [comment]
No preference, but I am enjoying the Web version greatly! Thank you for building this, it's harder to get this information than it should be, and this is making it much more accessible.

**Comment by DevClate** [comment]
Appreciate the feedback, and glad it’s been helpful for you! Let me take a look tomorrow and see. I’ll check to see if the 2.1 features need to be Entra “certified” as well.

**Comment by DevClate** [comment]
> No preference, but I am enjoying the Web version greatly! Thank you for building this, it's harder to get this information than it should be, and this is making it much more accessible.

Take a look at the web version, you may see something you like. Right now I'm just pulling if it has 2.1 in the description, but going forward going to see if I can pull from the Fido Alliance list. Curious, would you rather just have the highest capable, or all supported versions, such as if its a 2.1 is it assumed it can be 2.0, and does that make a difference? Woud love your thoughts.

Also I will be creating a PowerShell function for this, then I'll close out the issue. Thanks

**Comment by DevClate** [comment]
> Highest capable is the route I'd go, as so far the standard has been backwards compatible. You may want to parse for WebauthN 2.1 as well, as there seems to be some confusion about how to present this. For example Yubico lists this as "FIDO2 CTAP2.1" on their tech specs (I think this is only in the 5.7 firmware, but I'd need to dig deeper to see when this changed), See: https://www.yubico.com/ca/product/yubikey-5-series/yubikey-5c-nfc/ But Token2 lists this as "FIDO2.1 WebAuthn". See: https://www.token2.com/shop/product/token2-t2f2-pin-typec-fido2-u2f-and-totp-security-key-with-pin-complexity-feature
> 
> I think the correct way to describe this is CTAP2.1, but I'm not confident... In any event, the new functionality looks great!

Added FIDOVersion to PowerShell module that now checks the last entry version per the FIDO Alliance API, also shows in the web version. How does it look? Ok to close?

**Comment by matthew-armitage-steeves** [comment]
This looks great, and matches up with the best info I could find in my research. 
I wish Yubico would note the firmware version in their product name and submission to the FIDO Alliance, but that's a Yubico problem, not a you problem :).
I'd say that this comprehensively answers my request!
Thanks again for this resource, it's helping me in my quest to collect tokens for evaluation, Pokemon style.

**Comment by DevClate** [comment]
> This looks great, and matches up with the best info I could find in my research. I wish Yubico would note the firmware version in their product name and submission to the FIDO Alliance, but that's a Yubico problem, not a you problem :). I'd say that this comprehensively answers my request! Thanks again for this resource, it's helping me in my quest to collect tokens for evaluation, Pokemon style.

No problem Matthew! Maybe send them an email and/or tag them on socials? If they don't, I'm assuming any features are only on the newest firmware. Let me know if you see anything else, appreciate the feedback!
